# Java Gradle CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk@sha256:7be33522f6f0ca65c2e78b22b1ef3e6739038494c1de1b8fb6d96da400dccf53

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - gradle-cache

      # Gradle Wrapper
      # - run: sudo chmod +x gradlew
      # - run: ./gradlew --version
      # - run: ./gradlew clean build

      # Gradle
      - run: gradle --version
      - run: gradle clean build
      - run: gradle upload
      # - run: gradle publishGprPublicationToGitHubPackagesRepository

      - store_artifacts:
          path: ./build/libs

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache
